### ISSUE TITLE
Kinemic Band SDK Number Input Support.

### ISSUE THREAD

**Issue by JustDoIt9** [kinemic/kinemic-sdk-example-android#2]
Dear developer team.
I am gonna implement number input using kinemic gesture band like video below.
https://www.youtube.com/watch?v=8MxwRju4r8k
But in the android sdk, there is no registering function about DigitalInputListener.
Number input is not implement yet in android?
If so, when this function can be embedded in android sdk?
Thanks.

**Comment by fwinnen** [comment]
Hi,

our OnDigitListener as seen in the video is currently in BETA state.
You can access it with other BETA APIs using our EngineDevelop.

I created a develop branch [here](https://github.com/kinemic/kinemic-gesture-sdk-example-android/commit/fb4bc67d8972e51211d7fc1df8623e0fb8c22977) which shows the changes needed to create a EngineDevelop.

In summary:

1. Make sure you use our gradle-dev repository in your projects build.gradle:
```gradle
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://kinemic.jfrog.io/kinemic/gradle-dev" }
    }
}
```

2. Change dependency in modules build.gradle from gesture-sdk to gesture-sdk-develop:
```gradle
dependencies {
    ...
    implementation 'de.kinemic:gesture-sdk-develop:1.1.0-dev.22'
}
```

3. Change Engine to EngineDevelop in kotlin/java code:
```java
mEngine = new EngineDevelop(getApplicationContext());
```

Best Regards,
Fabian

**Comment by JustDoIt9** [comment]
Thanks!
